export const filterData=[{name:"Comida Rapida", Image: require('../../assets/fast-food.png'), id:"0"},
                        {name:"Hamburguesas", Image: require('../../assets/burger.png'), id:"1"},
                        {name:"Ensaladas", Image: require('../../assets/salad.png'), id:"2"},
                        {name:"Comida Marina", Image: require('../../assets/ceviches.png'), id:"3"},
                        {name:"Makis", Image: require('../../assets/makis.png'), id:"4"},
                        {name:"Comida Criolla", Image: require('../../assets/criolla.jpg'), id:"5"},
                        {name:"Sopas", Image: require('../../assets/sopas.png'), id:"6"},
];

export const restaurantsData=[
    {restaurantName:"MC Donals", farAway:"21.2",
    businessAddres:"22 Bessie street, Cape Town",images:'https://media.ambito.com/p/d02fefb4f1a1e88319266beab37fdc38/adjuntos/239/imagenes/040/446/0040446811/730x0/smart/mccrispy-chicken-1jpg.jpg',
    averageReview:4.9, numberOfReviw:272, coordinates:{lat:-26.1888612, lng:28.246325}, discounr:10, deliveryTime:15,
    collectTime:5, foodTipe:"Burgers, Wraps, milkshakes...",
    productData:[{name:"Hand cut chips", price:29.30,image:"https://mcdonalds.com.au/sites/mcdonalds.com.au/files/product-Fries-desktop.png"},
    {name:"Big Mac", price:50.80,image:"https://cache-backend-mcd.mcdonaldscupones.com/media/image/product$kpXxAHcZ/200/200/original?country=pe"},
    {name:"Chiken Burger", price:70, image:"https://mcdonaldsblog.in/wp-content/uploads/2021/09/mcChicken-burger-1.jpg"}],
    id:0},
    {restaurantName:"KFC", farAway:"21.2",
    businessAddres:"22 Bessie street, Cape Town",images:'https://media.ambito.com/p/d02fefb4f1a1e88319266beab37fdc38/adjuntos/239/imagenes/040/446/0040446811/730x0/smart/mccrispy-chicken-1jpg.jpg',
    averageReview:4.9, numberOfReviw:272, coordinates:{lat:-26.1888612, lng:28.246325}, discounr:10, deliveryTime:15,
    collectTime:5, foodTipe:"Burgers, Wraps, milkshakes...",
    productData:[{name:"Hand cut chips", price:29.30,image:"https://mcdonalds.com.au/sites/mcdonalds.com.au/files/product-Fries-desktop.png"},
    {name:"Big Mac", price:50.80,image:"https://cache-backend-mcd.mcdonaldscupones.com/media/image/product$kpXxAHcZ/200/200/original?country=pe"},
    {name:"Chiken Burger", price:70, image:"https://mcdonaldsblog.in/wp-content/uploads/2021/09/mcChicken-burger-1.jpg"}],
    id:1},
    {restaurantName:"Steers", farAway:"21.2",
    businessAddres:"22 Bessie street, Cape Town",images:'https://media.ambito.com/p/d02fefb4f1a1e88319266beab37fdc38/adjuntos/239/imagenes/040/446/0040446811/730x0/smart/mccrispy-chicken-1jpg.jpg',
    averageReview:4.9, numberOfReviw:272, coordinates:{lat:-26.1888612, lng:28.246325}, discounr:10, deliveryTime:15,
    collectTime:5, foodTipe:"Burgers, Wraps, milkshakes...",
    productData:[{name:"Hand cut chips", price:29.30,image:"https://mcdonalds.com.au/sites/mcdonalds.com.au/files/product-Fries-desktop.png"},
    {name:"Big Mac", price:50.80,image:"https://cache-backend-mcd.mcdonaldscupones.com/media/image/product$kpXxAHcZ/200/200/original?country=pe"},
    {name:"Chiken Burger", price:70, image:"https://mcdonaldsblog.in/wp-content/uploads/2021/09/mcChicken-burger-1.jpg"}],
    id:2},
    {restaurantName:"Roman Pizza", farAway:"21.2",
    businessAddres:"22 Bessie street, Cape Town",images:'https://media.ambito.com/p/d02fefb4f1a1e88319266beab37fdc38/adjuntos/239/imagenes/040/446/0040446811/730x0/smart/mccrispy-chicken-1jpg.jpg',
    averageReview:4.9, numberOfReviw:272, coordinates:{lat:-26.1888612, lng:28.246325}, discounr:10, deliveryTime:15,
    collectTime:5, foodTipe:"Burgers, Wraps, milkshakes...",
    productData:[{name:"Hand cut chips", price:29.30,image:"https://mcdonalds.com.au/sites/mcdonalds.com.au/files/product-Fries-desktop.png"},
    {name:"Big Mac", price:50.80,image:"https://cache-backend-mcd.mcdonaldscupones.com/media/image/product$kpXxAHcZ/200/200/original?country=pe"},
    {name:"Chiken Burger", price:70, image:"https://mcdonaldsblog.in/wp-content/uploads/2021/09/mcChicken-burger-1.jpg"}],
    id:3},
]
